# Generated by Django 5.2.11 on 2026-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('passanger_class', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('sibling_spouse_count', models.PositiveSmallIntegerField()),
                ('parent_child_count', models.PositiveSmallIntegerField()),
                ('fare', models.FloatField()),
                ('embarked_port', models.CharField(max_length=1)),
                ('predicted_survival', models.BooleanField()),
                ('probability', models.FloatField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
