# Generated by Django 5.2.11 on 2026-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_class', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('fare', models.FloatField()),
                ('embarked', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('predicted_survival', models.BooleanField()),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
